//! JS8's CRC-12 over the 75-bit payload.
//!
//! Two details here are load-bearing and neither is guessable:
//!
//! 1. It is an **augmented** CRC — the message bits shift straight into the
//!    register and the register is flushed by the trailing zero bits, rather
//!    than the more common form that XORs each byte into the top. JS8Call gets
//!    this from `boost::augmented_crc<12, 0xc06>` (`lib/crc12.cpp`).
//! 2. The result is **XORed with 42** (`lib/js8/genjs8.f90:48`). That has no
//!    counterpart in WSJT-X and no stated reason; the upstream comment is
//!    `TODO: jsherer - could change the crc here`. Omit it and every correct
//!    codeword fails verification, so the decoder finds signals, converges on
//!    them, and reports nothing at all.
//!
//! The known-answer vectors in the tests were produced by compiling JS8Call's
//! own `crc12.cpp` against boost, so they are outside-our-code evidence rather
//! than a restatement of what this file does.

/// Truncated CRC polynomial, `lib/crc12.cpp`.
const POLY: u16 = 0xc06;

/// Applied to the raw CRC before it goes on the wire, `lib/js8/genjs8.f90:48`.
const FINAL_XOR: u16 = 42;

const MASK: u16 = 0x0fff;

/// Bits of message payload ahead of the frame-type field.
pub const MSG_BITS: usize = 72;
/// Frame-type ("i3bit") field width.
pub const TYPE_BITS: usize = 3;
/// Payload guarded by the CRC.
pub const PAYLOAD_BITS: usize = MSG_BITS + TYPE_BITS;
/// Width of the CRC itself.
pub const CRC_BITS: usize = 12;

/// Boost's augmented CRC: message bits enter the register at the LSB, and the
/// polynomial is applied whenever a one leaves the top.
fn augmented(data: &[u8]) -> u16 {
    let mut rem: u16 = 0;
    for byte in data {
        for shift in (0..8).rev() {
            let bit = (byte >> shift) & 1;
            let top = rem & (1 << (CRC_BITS - 1)) != 0;
            rem = ((rem << 1) | u16::from(bit)) & MASK;
            if top {
                rem ^= POLY;
            }
        }
    }
    rem
}

/// CRC of a 75-bit payload: 72 message bits then 3 frame-type bits, each one
/// byte per element, MSB-first within the logical field.
///
/// The byte layout mirrors `lib/js8/genjs8.f90:41-47` exactly — nine bytes of
/// message, the frame type in the top three bits of the tenth, and an eleventh
/// zero byte that flushes the register.
pub fn crc12(payload: &[u8]) -> u16 {
    debug_assert_eq!(payload.len(), PAYLOAD_BITS);
    let mut buf = [0u8; 11];
    for (i, &bit) in payload.iter().take(MSG_BITS).enumerate() {
        if bit != 0 {
            buf[i >> 3] |= 0x80 >> (i & 7);
        }
    }
    let mut frame_type = 0u8;
    for &bit in &payload[MSG_BITS..PAYLOAD_BITS] {
        frame_type = (frame_type << 1) | (bit & 1);
    }
    buf[9] = (frame_type << 5) & 0b1110_0000;
    augmented(&buf) ^ FINAL_XOR
}

/// True when the trailing 12 bits of an 87-bit information word match a CRC
/// recomputed over the 75 that precede them.
///
/// This is the receive-side counterpart of [`crc12`] and is deliberately
/// symmetric with it. JS8Call's own `crc12_check` takes a different route —
/// it overwrites the frame-type byte with the CRC and re-runs the augmented
/// remainder — which does not round-trip against its own encoder for the
/// frame-type bits. Recomputing is unambiguous and matches what the encoder
/// actually transmitted.
pub fn check(info: &[u8]) -> bool {
    if info.len() < PAYLOAD_BITS + CRC_BITS {
        return false;
    }
    let mut got = 0u16;
    for &bit in &info[PAYLOAD_BITS..PAYLOAD_BITS + CRC_BITS] {
        got = (got << 1) | u16::from(bit & 1);
    }
    got == crc12(&info[..PAYLOAD_BITS])
}

/// Write a 12-bit CRC into `info[75..87]`, MSB-first.
pub fn place(info: &mut [u8], crc: u16) {
    for i in 0..CRC_BITS {
        info[PAYLOAD_BITS + i] = ((crc >> (CRC_BITS - 1 - i)) & 1) as u8;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `(nine message bytes, frame type, expected CRC)`.
    ///
    /// Generated by compiling JS8Call's `lib/crc12.cpp` against boost and
    /// driving it exactly as `lib/js8/genjs8.f90:41-48` does, including the
    /// XOR with 42. See `vendor/js8call/PROVENANCE.md`.
    const VECTORS: &[([u8; 9], u8, u16)] = &[
        ([0x3c, 0x6a, 0xbf, 0xd5, 0x47, 0x3c, 0xb7, 0xed, 0xb1], 0, 0x5ae),
        ([0x66, 0xec, 0x17, 0xde, 0x97, 0x6f, 0xed, 0x2a, 0xdd], 1, 0xbee),
        ([0x1b, 0x73, 0xa8, 0xdc, 0x79, 0x84, 0x9e, 0x48, 0x22], 2, 0x0fe),
        ([0x0e, 0x5b, 0x2d, 0x3e, 0x4c, 0xb4, 0xc5, 0x8c, 0x33], 3, 0x406),
        ([0x26, 0x65, 0x94, 0x16, 0x74, 0xe8, 0x30, 0x66, 0xcf], 4, 0xe74),
        ([0x5e, 0xd6, 0xfc, 0xa8, 0x23, 0x1d, 0xb8, 0xbc, 0x85], 5, 0x044),
        ([0xac, 0xf7, 0x01, 0xfb, 0x89, 0x03, 0x96, 0xe9, 0x10], 6, 0x7d2),
        ([0x2b, 0xbc, 0xd9, 0xbf, 0x17, 0x6a, 0xb2, 0x10, 0x51], 7, 0x57c),
        ([0x9a, 0xee, 0xd0, 0x0c, 0xeb, 0x10, 0xab, 0xdf, 0xd6], 0, 0x464),
        ([0x8b, 0x86, 0xf7, 0xd4, 0xa7, 0x7e, 0x77, 0xf6, 0x5b], 1, 0x8e4),
        ([0x9f, 0x32, 0x61, 0xbc, 0xcb, 0xe2, 0xc2, 0x3b, 0xdc], 2, 0x050),
        ([0x91, 0x52, 0x33, 0x6c, 0xe6, 0xcc, 0xa2, 0x91, 0x2a], 3, 0x658),
        ([0x21, 0xe8, 0x08, 0xa8, 0x4a, 0x35, 0x34, 0xf6, 0xd1], 4, 0x34c),
        ([0x3d, 0x8a, 0xe8, 0x32, 0x42, 0xd9, 0xd9, 0x8b, 0x92], 5, 0x91c),
        ([0x49, 0x26, 0x80, 0xb5, 0x22, 0x05, 0xe9, 0xe4, 0x8d], 6, 0x146),
        ([0x3f, 0x6b, 0xbb, 0x10, 0x9c, 0x73, 0x85, 0x7a, 0x5d], 7, 0x384),
        ([0x0b, 0xea, 0x73, 0x72, 0x75, 0xb0, 0x45, 0xf1, 0x54], 0, 0xd30),
        ([0x64, 0x1d, 0xd4, 0x2b, 0x19, 0x33, 0x7e, 0x81, 0x39], 1, 0x26e),
        ([0x77, 0x31, 0x40, 0xde, 0x71, 0xf1, 0x15, 0x54, 0x5c], 2, 0x872),
        ([0xcb, 0xe8, 0xde, 0x42, 0xe1, 0xad, 0xdb, 0x2a, 0xfe], 3, 0x42c),
        ([0x96, 0x4e, 0xcd, 0xc4, 0xd3, 0xb1, 0x59, 0x6a, 0x01], 4, 0xf58),
        ([0xa7, 0x87, 0x7a, 0x27, 0x11, 0x81, 0x60, 0xcc, 0x5b], 5, 0x95a),
        ([0x38, 0x4b, 0xfc, 0x81, 0x18, 0x3d, 0xbe, 0x67, 0x7a], 6, 0xda6),
        ([0x12, 0x98, 0x04, 0xa1, 0x49, 0xa7, 0xbb, 0xd2, 0x5e], 7, 0x3e8),
        ([0; 9], 0, 0x02a),
        ([0; 9], 1, 0x420),
        ([0; 9], 2, 0x83e),
        ([0; 9], 3, 0xc34),
        ([0; 9], 4, 0xc04),
        ([0; 9], 5, 0x80e),
        ([0; 9], 6, 0x410),
        ([0; 9], 7, 0x01a),
    ];

    fn payload(msg: &[u8; 9], frame_type: u8) -> Vec<u8> {
        let mut bits = Vec::with_capacity(PAYLOAD_BITS);
        for byte in msg {
            for shift in (0..8).rev() {
                bits.push((byte >> shift) & 1);
            }
        }
        for shift in (0..TYPE_BITS).rev() {
            bits.push((frame_type >> shift) & 1);
        }
        bits
    }

    #[test]
    fn matches_js8call_known_answers() {
        for (msg, frame_type, want) in VECTORS {
            let got = crc12(&payload(msg, *frame_type));
            assert_eq!(got, *want, "msg {msg:02x?} type {frame_type}");
        }
    }

    #[test]
    fn an_all_zero_payload_returns_the_final_xor_alone() {
        // The augmented remainder of all zeros is zero, so anything other than
        // 42 here means the XOR was dropped or applied twice.
        assert_eq!(crc12(&payload(&[0; 9], 0)), FINAL_XOR);
    }

    #[test]
    fn check_accepts_what_crc12_produced() {
        for (msg, frame_type, _) in VECTORS {
            let mut info = payload(msg, *frame_type);
            let crc = crc12(&info);
            info.resize(PAYLOAD_BITS + CRC_BITS, 0);
            place(&mut info, crc);
            assert!(check(&info), "msg {msg:02x?} type {frame_type}");
        }
    }

    #[test]
    fn check_rejects_a_single_flipped_payload_bit() {
        let mut info = payload(&VECTORS[0].0, VECTORS[0].1);
        let crc = crc12(&info);
        info.resize(PAYLOAD_BITS + CRC_BITS, 0);
        place(&mut info, crc);
        for i in 0..PAYLOAD_BITS {
            info[i] ^= 1;
            assert!(!check(&info), "flipping payload bit {i} went unnoticed");
            info[i] ^= 1;
        }
    }

    #[test]
    fn the_frame_type_is_covered_by_the_crc() {
        // The frame type rides in the CRC's byte 9, and an implementation that
        // forgot it would still pass every message-only test above.
        let crcs: Vec<u16> = (0..8).map(|t| crc12(&payload(&[0; 9], t))).collect();
        for (i, a) in crcs.iter().enumerate() {
            for b in &crcs[i + 1..] {
                assert_ne!(a, b, "two frame types share a CRC");
            }
        }
    }
}
