//! Dictionary-compressed free text — the other data-frame path.
//!
//! Where [`super::huff`] codes free text a character at a time, this substitutes
//! whole words from a 262 144-entry dictionary shared by every JS8 station. A
//! common word costs as little as five bits, so ordinary English fits far more
//! text into a 72-bit frame than Huffman can: "THE QUICK BROWN FOX" takes 16
//! characters' worth of Huffman but compresses whole. The transmitter tries
//! both and keeps whichever carried more, which is why both have to exist.
//!
//! ## The codeword
//!
//! An index becomes a run of 4-bit digits terminated by a 4-bit value below
//! `S`, followed by one flag bit saying whether a space follows the word.
//! Digits at or above `S` are continuation digits in base `C`; the terminator
//! carries the low `S`-ary digit. Reconstruction adds a per-length base offset,
//! which is what makes the code prefix-free across lengths:
//!
//! ```text
//! j = 0; for each continuation digit d: j = j*C + (d - S)
//! index = j*S + terminator + BASE[number of continuation digits]
//! ```
//!
//! ## The dictionary
//!
//! Upstream ships the table twice — once by index, once alphabetically — as
//! 12 MB of C++ source. We store only the index-ordered form, deflated to about
//! 1 MB (`jsc_dict.bin`, produced by `tools/gen_js8_jsc.py`), and rebuild the
//! alphabetical ordering at load. Two shipped tables can disagree; one cannot.
//!
//! The words are Latin-1, not UTF-8 — 32 entries are extended characters — so
//! they are decoded as such rather than assumed to be ASCII.

use std::collections::HashMap;
use std::io::Read;
use std::sync::OnceLock;

/// Digit width, in bits.
const B: u32 = 4;
/// Values below this terminate a codeword; at or above, they continue it.
const S: u32 = 7;
/// Radix of the continuation digits.
const C: u32 = (1 << B) - S;

/// Per-length base offsets, so codewords of different lengths cannot collide.
fn bases() -> [u32; 8] {
    let mut base = [0u32; 8];
    let mut term = S;
    for k in 1..8 {
        base[k] = base[k - 1] + term;
        term *= C;
    }
    base
}

struct Dict {
    /// Words in index order.
    words: Vec<String>,
    /// Word to lowest index, rebuilt from `words`.
    index: HashMap<String, u32>,
}

static DICT: OnceLock<Dict> = OnceLock::new();

/// The deflated dictionary, generated by `tools/gen_js8_jsc.py`.
const BLOB: &[u8] = include_bytes!("jsc_dict.bin");

fn dict() -> &'static Dict {
    DICT.get_or_init(|| {
        let mut raw = Vec::new();
        flate2::read::ZlibDecoder::new(BLOB)
            .read_to_end(&mut raw)
            .expect("the bundled JSC dictionary is corrupt");
        assert_eq!(&raw[..4], b"JS8D", "the bundled JSC dictionary has the wrong magic");
        let count = u32::from_le_bytes(raw[4..8].try_into().expect("count")) as usize;

        let lens = &raw[8..8 + count];
        let mut at = 8 + count;
        let mut words = Vec::with_capacity(count);
        for &len in lens {
            let len = len as usize;
            // Latin-1: every byte is a code point, which is not true of UTF-8.
            words.push(raw[at..at + len].iter().map(|&b| char::from(b)).collect::<String>());
            at += len;
        }

        let mut index = HashMap::with_capacity(count);
        for (i, w) in words.iter().enumerate() {
            index.entry(w.clone()).or_insert(i as u32);
        }
        Dict { words, index }
    })
}

/// Entries in the dictionary.
pub fn size() -> usize {
    dict().words.len()
}

/// The word at `index`, if there is one.
pub fn word(index: u32) -> Option<&'static str> {
    dict().words.get(index as usize).map(String::as_str)
}

/// The index of `word`, if the dictionary has it.
pub fn index_of(word: &str) -> Option<u32> {
    dict().index.get(word).copied()
}

/// The longest dictionary word that prefixes `text`, and its index.
///
/// Compression is greedy: take the longest match, emit it, continue. Upstream
/// does the same, so encoding the same text produces the same frame.
pub fn longest_prefix(text: &str) -> Option<(usize, u32)> {
    let d = dict();
    // No dictionary word is longer than this, so there is no point looking
    // further ahead.
    let max = text.len().min(26);
    for len in (1..=max).rev() {
        if !text.is_char_boundary(len) {
            continue;
        }
        if let Some(&i) = d.index.get(&text[..len]) {
            return Some((len, i));
        }
    }
    None
}

/// Append the codeword for `index` to `bits`, flagging a following space.
pub fn encode_index(bits: &mut Vec<u8>, index: u32, space_after: bool) {
    let base = bases();
    // Find how many continuation digits this index needs.
    let mut k = 0usize;
    while k + 1 < base.len() && index >= base[k + 1] {
        k += 1;
    }
    let rest = index - base[k];
    let terminator = rest % S;
    let mut j = rest / S;

    // Continuation digits are most-significant first, so build then reverse.
    let mut digits = Vec::new();
    for _ in 0..k {
        digits.push(((j % C) + S) as u8);
        j /= C;
    }
    for d in digits.into_iter().rev() {
        for i in (0..B).rev() {
            bits.push((d >> i) & 1);
        }
    }
    for i in (0..B).rev() {
        bits.push(((terminator as u8) >> i) & 1);
    }
    bits.push(u8::from(space_after));
}

/// Compress `text`, appending to `bits`, stopping before anything that would
/// not fit in `capacity`. Returns how many characters were consumed.
///
/// The text is split on spaces **first** and prefix matching runs only within
/// each word (`jsc.cpp`'s `compress`). Matching across a space would find
/// longer dictionary entries and compress better — but it would also produce
/// frames no other station generates, so the worse-compressing behaviour is
/// the correct one.
///
/// A space is not encoded; it rides as a flag on the last codeword of the word
/// that precedes it.
pub fn compress_into(bits: &mut Vec<u8>, text: &str, capacity: usize) -> usize {
    let mut used = 0usize;
    let words: Vec<&str> = text.split(' ').collect();
    let last_word = words.len().saturating_sub(1);

    for (i, word) in words.iter().enumerate() {
        let is_last_word = i == last_word;
        // An empty part is a run of consecutive spaces, which upstream encodes
        // as a literal space character — except at the very end.
        let (mut rest, is_space_character) =
            if word.is_empty() && !is_last_word { (" ", true) } else { (*word, false) };

        while !rest.is_empty() {
            let Some((len, index)) = longest_prefix(rest) else { return used };
            let remaining = &rest[len..];
            let append_space = remaining.is_empty() && !is_space_character && !is_last_word;

            let mut candidate = Vec::new();
            encode_index(&mut candidate, index, append_space);
            // Strictly less than, as upstream tests it: a codeword that would
            // exactly fill the frame is rejected rather than accepted.
            if bits.len() + candidate.len() >= capacity {
                return used;
            }
            bits.extend_from_slice(&candidate);
            used += len + usize::from(append_space);
            rest = remaining;
        }
    }
    used
}

/// Decompress a codeword stream back to text.
pub fn decompress(bits: &[u8]) -> String {
    let base = bases();
    let d = dict();

    // First pass: split the stream into 4-bit digits, noting where a
    // terminator's trailing flag bit asked for a space.
    let mut digits: Vec<u32> = Vec::new();
    let mut spaces: Vec<usize> = Vec::new();
    let mut i = 0usize;
    while i + B as usize <= bits.len() {
        let value = bits[i..i + B as usize].iter().fold(0u32, |a, &b| (a << 1) | u32::from(b));
        digits.push(value);
        i += B as usize;
        if value < S {
            // Terminators carry one extra flag bit.
            if i < bits.len() && bits[i] == 1 {
                spaces.push(digits.len() - 1);
            }
            i += 1;
        }
    }

    let mut out = String::new();
    let mut start = 0usize;
    while start < digits.len() {
        let mut k = 0usize;
        let mut j = 0u32;
        while start + k < digits.len() && digits[start + k] >= S {
            j = j * C + (digits[start + k] - S);
            k += 1;
        }
        if start + k >= digits.len() || k >= base.len() {
            break;
        }
        let Some(index) = j
            .checked_mul(S)
            .and_then(|v| v.checked_add(digits[start + k]))
            .and_then(|v| v.checked_add(base[k]))
        else {
            break;
        };
        let Some(w) = d.words.get(index as usize) else { break };
        out.push_str(w);
        if spaces.contains(&(start + k)) {
            out.push(' ');
        }
        start += k + 1;
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_dictionary_loads_and_is_the_expected_size() {
        assert_eq!(size(), 262_144);
        // The first entries are the single most common letters, which is a
        // cheap check that the index order survived the blob round trip.
        assert_eq!(word(0), Some("E"));
        assert_eq!(word(1), Some("T"));
        assert_eq!(word(2), Some("A"));
    }

    #[test]
    fn the_extended_latin1_entries_are_present() {
        // Thirty-two entries are extended Latin-1 characters written as escaped
        // bytes in upstream's source. A generator that dropped them would shift
        // every index past 10704 and corrupt most of the dictionary.
        let word = word(10_704).expect("entry 10704");
        assert_eq!(word.chars().count(), 1);
        assert!(!word.is_ascii(), "expected an extended character, got {word:?}");
    }

    #[test]
    fn indices_round_trip_through_the_codeword() {
        // Cover every codeword length the base table supports.
        for index in [0u32, 1, 6, 7, 8, 62, 63, 64, 500, 5_000, 50_000, 262_143] {
            for space in [false, true] {
                let mut bits = Vec::new();
                encode_index(&mut bits, index, space);
                let text = decompress(&bits);
                let expect =
                    format!("{}{}", word(index).expect("word"), if space { " " } else { "" });
                assert_eq!(text, expect, "index {index} space {space}");
            }
        }
    }

    #[test]
    fn common_words_cost_very_little() {
        // The whole point of the dictionary. Note that not every English word
        // is an entry — "THE" is not — because matching is by longest prefix
        // and short fragments compose. These are entries.
        for w in ["AND", "QSO", "CQ", "GOOD"] {
            let mut bits = Vec::new();
            encode_index(&mut bits, index_of(w).unwrap_or_else(|| panic!("{w}")), true);
            assert!(bits.len() <= 15, "{w} cost {} bits", bits.len());
        }
    }

    #[test]
    fn words_absent_from_the_dictionary_still_compress_by_prefix() {
        // "THE" has no entry of its own, so the greedy matcher has to build it
        // from shorter ones. A matcher that only did whole-word lookup would
        // fail here and silently fall back to Huffman for most English.
        let mut bits = Vec::new();
        assert!(index_of("THE").is_none(), "the premise of this test changed");
        let used = compress_into(&mut bits, "THE", super::super::huff::FRAME_BITS);
        assert_eq!(used, 3);
        assert_eq!(decompress(&bits), "THE");
    }

    #[test]
    fn text_round_trips_through_compression() {
        for text in ["THE QUICK BROWN FOX", "HELLO WORLD", "GOOD MORNING", "WEATHER IS FINE"] {
            let mut bits = Vec::new();
            let used = compress_into(&mut bits, text, super::super::huff::FRAME_BITS);
            assert_eq!(used, text.len(), "{text} did not fit");
            assert_eq!(decompress(&bits), *text, "{text}");
        }
    }

    #[test]
    fn compression_beats_huffman_on_ordinary_english() {
        // This is the reason both codecs exist; if it stops being true, the
        // transmitter is choosing the wrong one.
        let text = "THE QUICK BROWN FOX";
        let mut jsc = Vec::new();
        let jsc_used = compress_into(&mut jsc, text, super::super::huff::FRAME_BITS);
        let mut huff = Vec::new();
        let huff_used =
            super::super::huff::encode_into(&mut huff, text, super::super::huff::FRAME_BITS);
        assert!(jsc_used > huff_used, "jsc {jsc_used} chars vs huffman {huff_used}");
    }

    #[test]
    fn a_word_outside_the_dictionary_stops_compression() {
        let mut bits = Vec::new();
        // Long nonsense has no dictionary entry beyond its first characters.
        let used = compress_into(&mut bits, "ZZQXJ", super::super::huff::FRAME_BITS);
        assert!(used <= 5);
    }

    #[test]
    fn truncated_input_does_not_panic() {
        for len in 0..40 {
            let bits: Vec<u8> = (0..len).map(|i| (i % 2) as u8).collect();
            let _ = decompress(&bits);
        }
    }
}
